env: "prod"
storage_path: "./storage.db"
http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 30s
  user: "Shabby8574"
  password: "12345"
database:
  host: localhost
  port: 4050
  user: myuser
  password: 4050
  dbname: todolistdb
  sslmode: disable